# Generated by Django 4.0.3 on 2022-03-14 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='HouseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.CharField(blank=True, choices=[('for 2 People', 'Couple'), ('for 1 Person', 'Single'), ('for 5 to  10 People', 'Family'), ('for 10 People', 'For 10 People'), ('for 20 People', 'For 20 People'), ('for 30 People', 'For 30 People'), ('for 50 People', 'For Over 50 People')], default='for 1 Person', help_text="Choices are: [('for 2 People', 'Couple'), ('for 1 Person', 'Single'), ('for 5 to  10 People', 'Family'), ('for 10 People', 'For 10 People'), ('for 20 People', 'For 20 People'), ('for 30 People', 'For 30 People'), ('for 50 People', 'For Over 50 People')]", max_length=128)),
                ('location', models.CharField(blank=True, max_length=80, null=True)),
                ('guests', models.IntegerField(blank=True, default=1, null=True)),
                ('beds', models.IntegerField(blank=True, default=1, null=True)),
                ('bedrooms', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=140, null=True)),
                ('street', models.CharField(blank=True, max_length=140, null=True)),
                ('suite_code', models.CharField(blank=True, max_length=140, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_added', to=settings.AUTH_USER_MODEL)),
                ('ammenities', models.ManyToManyField(blank=True, null=True, to='booking.ammenities')),
                ('facilities', models.ManyToManyField(blank=True, related_name='rooms', to='booking.facility')),
                ('house_rules', models.ManyToManyField(blank=True, related_name='rooms', to='booking.houserule')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='booking.room')),
            ],
        ),
    ]
