# Generated by Django 4.0.3 on 2022-03-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ammenities',
        ),
        migrations.AddField(
            model_name='booking',
            name='ammenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='facilities',
        ),
        migrations.AddField(
            model_name='booking',
            name='facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='house_rules',
        ),
        migrations.AddField(
            model_name='booking',
            name='house_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.CharField(default='1', max_length=70),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='Ammenities',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='HouseRule',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
